// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okdttfsrfzkvpnkfqcoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZHR0ZnNyZnprdnBua2ZxY29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjY2NzAsImV4cCI6MjA2NDIwMjY3MH0.St2bjw14NTtXoNLpt2MXNMrdnJeUIlhOZb-Gc9WS7vI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);